### ISSUE TITLE
Module: Visualizing a time series of rasters via leaflet.

### ISSUE THREAD

**Issue by mateuszwyszynski** [PredictiveEcology/SpaDES.shiny#14]
- RasterLayers: https://cran.r-project.org/web/packages/raster/vignettes/Raster.pdf
- Raster Images in Leaflet:
https://rstudio.github.io/leaflet/raster.html
- Working with Raster Data Time Series in R
http://neondataskills.org/tutorial-series/raster-time-series/

**Comment by mateuszwyszynski** [comment]
<img width="1014" alt="screen shot 2017-09-08 at 13 04 20" src="https://user-images.githubusercontent.com/30074645/30209027-45f7aa36-9496-11e7-98c3-a6c8c24ce5c8.png">

Currently we see four modules here: 

1. Display raster on a map
2. Display histogram
3. Time slider module with ability to simulate changing value from minimum to maximum (play)
4. Module that visualizes set of rasters on map over time. This module uses the three above.

The other option is to just create one module that visualizes set of rasters over time. However we believe that having four different modules is more robust. E.g. user can use just time slider module together with another module which displays a table in order to display a table that changes over time.

@eliotmcintire @achubaty - do you agree with this approach, i.e. having smaller modules that you can combine into a bigger one instead of having one module that implements all these components?

**Comment by achubaty** [comment]
Yes, splitting things up a bit is my preferred solution, as this allows the app developer to mix-and-match submodule components. For example, if I wanted pieces 1 and 2 but not 3, I can do so easily using a submodular approach, but using the other approach of one megamodule, I would need to copy/paste pieces of code out of it in order to get the functionality I want.
