### ISSUE TITLE
Create a module that displays raster on a map

### ISSUE THREAD

**Issue by DamianRodziewicz** [PredictiveEcology/SpaDES.shiny#22]

**Comment by mateuszwyszynski** [comment]
@eliotmcintire @achubaty 

We are currently working on this issue and we believe we could use your help with some clarifications. 

**A. How rasters are displayed in LandWeb App.** 
Displaying a raster takes place inside the `timeSinceFireMod` module which is defined in shinyModules.R file. This module works in the following way:

1. It creates a leaflet map
2. It uses leaflet proxy to update the current state of the map
3. There is a reactive value, `rasterInput`, which stores two things:
 - current raster
 - current slider value
4. Whenever `rasterInput` changes, leaflet proxy reacts and:
 - adds new tiles. These tiles take into account new raster to which `rasterInput` is now pointing
 - remove previous tiles (with concrete `layerId`)
5. Inside `rasterInput` reactive value there is a call to function `gdal2TilesFn`. This function uses `gdalUtils::gdaldem` to create a map from the raster (which, as said previously, is stored in `rasterInput`). 

**B. Questions**
1. Could you please confirm that our understanding of timeSinceFireMod is appropriate or correct us wherever we are mistaken?
2. I can see multiple lines commented out. From what I see there, you have tried multiple ways of implementing this feature. Could you please tell us why you have decided to choose this final option? Why not use `addRasterImage` for instance?
3. This is connected to the previous question: during the call to leaflet proxy we use .png files to add tiles. Is it necessary, from your perspective, to first convert raster into .png file? 
4. Also, why are these .png files split into multiple files containing parts of raster? Is it because they have to fit into the tiles previously added to map? The ones added when creating the map?
5. Could you briefly explain how the `gdal2Tiles` function works?

**Comment by achubaty** [comment]
@eliotmcintire will need to speak to many of those details in implementation, but if I recall correctly, the purpose of `gdal2TilesFn` is to create the various subsets of the raster at different zoom levels (tiles) via a system call to python/gdal (which is MUCH faster than doing it the R, if that functionality even exists in R). Once multiple sets of tiles are generated for multiple zoom levels, it's much faster to zoom in/out on the map.

**Comment by eliotmcintire** [comment]
addRasterImage is WAY too slow for large rasters. Converting the large
raster to many tiles using gdal allows for arbitrarily large rasters to be
displayed. That is how leaflet works with its base layers. For this to
work, the raster must be built into a series of small png files (tiles),
leaflet and the html do the rest.
